name: macOS

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  workflow_dispatch:

#env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Release


defaults:
  run:
    shell: bash

jobs:
  build-macos:
    name: Build MacOS
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12 ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Configure CMake [Debug]
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-debug" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Show compile commands [Debug]
        run: cat build-debug/compile_commands.json
      - name: Build [Debug]
        run: cmake --build "${{github.workspace}}/build-debug" --config Debug -j
      - name: Test [Debug]
        working-directory: ${{github.workspace}}/build-debug
        run: ctest -C Debug --output-on-failure -j
      - name: Install [Debug]
        run: cmake --install "${{github.workspace}}/build-debug" --config Debug
      - name: Configure CMake [Release]
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-release" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Show compile commands [Release]
        run: cat build-release/compile_commands.json
      - name: Build [Release]
        run: cmake --build "${{github.workspace}}/build-release" --config Release -j
      - name: Test [Release]
        working-directory: ${{github.workspace}}/build-release
        run: ctest -C Release --verbose
      - name: Install [Release]
        run: cmake --install "${{github.workspace}}/build-release" --config Release
