name: macOS

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  workflow_dispatch:

#env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Release


defaults:
  run:
    shell: bash

jobs:
  build-macos:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images#available-images
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories  (os-labels : macos-12)
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software-for-github-owned-images
        #os: [ macos-15-large, macos-15-xlarge, macos-14-large, macos-14-xlarge, macos-13-large, macos-13-xlarge ]  #  macos-latest  ==  macos-14 == macos-14-xlarge
        #  NOTE :: macos-**-large and macos-**-xlarge are chargeable hence NOT added here
        os: [ macos-15, macos-14, macos-13 ]  #  macos-latest  ==  macos-14
#  NOTE : macos-*        : executes arm64 (instead of x64_64), which lowers FLOATING POINT precision similar to Windows
#         macos-*-large  : x86_64
#         macos-*-xlarge : arm64 lowers FLOATING POINT precision similar to Windows
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#language-and-runtime
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#language-and-runtime
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#language-and-runtime
          # clang++ == 'AppleClang-14'
          # default : [ macos-11 -> AppleClang-13 ,
          #             macos-12 -> AppleClang-14 ,
          #             macos-13 -> AppleClang-15 ,
          #             macos-14 -> AppleClang-15 ,
          #             macos-15 -> AppleClang-16 ]
        compiler: [ default, g++-14, g++-13, g++-12 ]
        exclude: [ # skipping a fix for g++-N compilers. refer thread https://github.com/iains/gcc-14-branch/issues/11
                   { os: macos-15, compiler: g++-14 },
                   { os: macos-15, compiler: g++-13 },
                   { os: macos-15, compiler: g++-12 } ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Compiler(s) Version
        run: echo "g++ --version"; g++ --version; echo ""; echo "clang++ --version"; clang++ --version; echo ""; bash -c 'COMPILER="${{matrix.compiler}}"; if [ "${COMPILER}" == "default" ]; then COMPILER="clang++"; fi; echo ""; echo "${COMPILER} --version"; ${COMPILER} --version'
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Get Version
        run: uname -a && echo "------------" && cmake --version && echo "------------" ; bash -c 'COMPILER="${{matrix.compiler}}"; if [ "${COMPILER}" == "default" ]; then COMPILER="clang++"; fi; ${COMPILER}  -dM -E -x c++ /dev/null | egrep -i "(apple|mach|gnu|clang|llvm|linux|WIN|version|major|minor)"'
      - name: Check Generators
        # https://stackoverflow.com/questions/25941536/what-is-a-cmake-generator
        run: cmake --help
      - name: Compiler Macros Available
        run: bash -c 'COMPILER="${{matrix.compiler}}"; if [ "${COMPILER}" == "default" ]; then COMPILER="clang++"; fi; ${COMPILER}  -dM -E -x c++ /dev/null'
      - name: Configure CMake (compiler=default) [Debug]
        if: matrix.compiler == 'default'
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-debug" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCONVERTER_TEST_OS_VERSION=${{matrix.os}}
      - name: Configure CMake (compiler=NOT-default) [Debug]
        if: matrix.compiler != 'default'
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-debug" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCONVERTER_TEST_OS_VERSION=${{matrix.os}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
      - name: Check Work-Around-Flags
        run: grep define "${{github.workspace}}/build-debug/include/converter/_workaroundConfig.h" | grep -v -e "^//" -e " e_[^ ]*_FEATURE "
      - name: Show compile commands [Debug]
        run: cat build-debug/compile_commands.json
      - name: Build [Debug]
        run: cmake --build "${{github.workspace}}/build-debug" --config Debug -j$(sysctl -n hw.ncpu)
      - name: Test [Debug]
        working-directory: ${{github.workspace}}/build-debug
        #run: ctest -C Debug --output-on-failure -j
        run: ctest -C Debug --verbose
      - name: Install [Debug]
        run: sudo cmake --install "${{github.workspace}}/build-debug" --config Debug
      - name: Configure CMake (compiler=default) [Release]
        if: matrix.compiler == 'default'
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-release" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Configure CMake (compiler=NOT-default) [Release]
        if: matrix.compiler != 'default'
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-release" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
      - name: Build [Release]
        run: cmake --build "${{github.workspace}}/build-release" --config Release -j$(sysctl -n hw.ncpu)
      - name: Test [Release]
        working-directory: ${{github.workspace}}/build-release
        run: ctest -C Release --verbose
      - name: Install [Release]
        run: sudo cmake --install "${{github.workspace}}/build-release" --config Release
