name: Parent Workflow

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  workflow_dispatch:
    # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
    # To enable a workflow to be triggered manually, you need to configure the workflow_dispatch event

permissions:
  contents: write

jobs:
  linux-sub-workflow:
    uses: ./.github/workflows/sub-workflow-linux.yml

  macos-sub-workflow:
    uses: ./.github/workflows/sub-workflow-macos.yml

  windows-sub-workflow:
    uses: ./.github/workflows/sub-workflow-windows.yml

  # Consolidate job - downloads artifacts from each sub-workflow's run
  consolidate:
    needs: [linux-sub-workflow, macos-sub-workflow, windows-sub-workflow]
    if: always() # Forces execution regardless of sub-workflow success/failure statuses
    uses: ./.github/workflows/sub-workflow-consolidate.yml
