name: Windows

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025-vs2026
            generator: "Visual Studio 18 2026"
            toolset_compiler: { compiler: default, toolset: -1, cmdShell: cmd, rawCompiler: cl.exe, compilerMacros: "echo msbuild_does_not_support" }
    runs-on: ${{matrix.os}}
    timeout-minutes: 3
    outputs:
      run-id: ${{ github.run_id }}

    defaults:
      run:
        shell: ${{matrix.toolset_compiler.cmdShell}}

    steps:
      - name: Setup msbuild
        if: matrix.toolset_compiler.compiler != 'g++'
        uses: microsoft/setup-msbuild@v2

      - name: Compiler Version
        if: matrix.toolset_compiler.compiler != 'g++'
        run: echo "msbuild.exe --version"; msbuild.exe --version; echo ""; echo "clang++ --version"; clang++ --version;

      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Get Version
        if: matrix.toolset_compiler.compiler == 'default'
        run: uname -a && echo "------------" && cmake --version && echo "------------"

      - name: Check Generators
        run: cmake --help

      - name: Compiler Macros Available
        run: ${{matrix.toolset_compiler.compilerMacros}}

      - name: Configure CMake (compiler=default) [Debug]
        if: matrix.toolset_compiler.compiler == 'default'
        run: |
          cmake --log-level=TRACE -G "${{matrix.generator}}" -A x64 -S "${{github.workspace}}" -B "${{github.workspace}}/build-debug" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
      - name: Check Work-Around-Flags
        run: |
          grep define "${{github.workspace}}/build-debug/include/converter/_workaroundConfig.h" | grep -v -e "^//" -e " e_[^ ]*_FEATURE "
          FLAG_DIR="${{github.workspace}}/build-debug/workAroundFlags"
          mkdir -p ${FLAG_DIR}
          FLAG_FILE="${FLAG_DIR}/flag-${{matrix.os}}-${{matrix.toolset_compiler.compiler}}.csv"
          echo "_OS,compiler,"$(grep "#define" "${{github.workspace}}/build-debug/include/converter/_workaroundConfig.h" | sed "s/  */ /g" | cut -d' ' -f2,3 | grep -e "^SUPPORTED_" -e "^HAS_" -e "^ENABLE_" | cut -d' ' -f1 | tr '\n' ',' | sed 's/,$/\n/g') > "${FLAG_FILE}"
          echo "${{matrix.os}},${{matrix.toolset_compiler.compiler}},"$(grep "#define" "${{github.workspace}}/build-debug/include/converter/_workaroundConfig.h" | sed "s/  */ /g" | cut -d' ' -f2,3 | grep -e "^SUPPORTED_" -e "^HAS_" -e "^ENABLE_" | cut -d' ' -f2 | tr '\n' ',' | sed 's/,$/\n/g') >> "${FLAG_FILE}"
          cat "${FLAG_FILE}"

      - name: Upload Artifact from Sub-Workflow
        uses: actions/upload-artifact@v4
        with:
          name: "artifact-${{matrix.os}}-${{matrix.toolset_compiler.compiler}}"
          path: "build-debug/workAroundFlags/flag-${{matrix.os}}-${{matrix.toolset_compiler.compiler}}.csv"

      - name: Build [Debug]
        if: matrix.toolset_compiler.compiler != 'g++'
        run: cmake --build "${{github.workspace}}/build-debug" --config Debug -j$(nproc) -- -m -nologo -verbosity:normal

      - name: Test [Debug]
        working-directory: ${{github.workspace}}/build-debug
        run: ctest -C Debug --verbose

      - name: Install [Debug]
        run: cmake --install "${{github.workspace}}/build-debug" --config Debug
