name: Windows

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  workflow_dispatch:

#env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Release


defaults:
  run:
    shell: cmd
    #shell: bash

jobs:
  build-windows:
    name: Build Windows
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images#available-images
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources  (os-labels : windows-2022)
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
        os: [windows-2019, windows-2022]
        # https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-T
        # CMake compiler option doesn't work for Visual Studio project :: https://youtrack.jetbrains.com/issue/CPP-17314
        toolset_compiler: [ default, ClangCl ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Configure CMake [Debug]
        # https://hungvu.tech/advanced-github-actions-conditional-workflow
        # https://samanpavel.medium.com/github-actions-conditional-job-execution-e6aa363d2867
        # https://docs.github.com/en/actions/learn-github-actions/expressions
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
        if: matrix.toolset_compiler == 'default'
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-debug" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
        if: matrix.toolset_compiler != 'default'
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-debug" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug  -T "${{matrix.toolset_compiler}}"
      - name: Build [Debug]
        run: cmake --build "${{github.workspace}}/build-debug" --config Debug -j   -- /m /nologo /verbosity:quiet
      - name: Test [Debug]
        working-directory: ${{github.workspace}}/build-debug
        run: ctest -C Debug --output-on-failure -j
      - name: Install [Debug]
        run: cmake --install "${{github.workspace}}/build-debug" --config Debug
      - name: Configure CMake [Release]
        if: matrix.toolset_compiler == 'default'
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-release" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
        if: matrix.toolset_compiler != 'default'
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-release" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release  -T "${{matrix.toolset_compiler}}"
      - name: Build [Release]
        run: cmake --build "${{github.workspace}}/build-release" --config Release -j   -- /m /nologo /verbosity:quiet
      - name: Test [Release]
        working-directory: ${{github.workspace}}/build-release
        run: ctest -C Release --verbose
      - name: Install [Release]
        run: cmake --install "${{github.workspace}}/build-release" --config Release
      - name: Check Work-Arounds
        shell: bash
        run: grep define "${{github.workspace}}/build-release/include/converter/_workaroundConfig.h" | grep -v -e "^//" -e " _e_"


