name: Windows

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - v*
  workflow_dispatch:

#env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Release


defaults:
  run:
    shell: bash

jobs:
  build-windows:
    name: Build Windows
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{matrix.os}}
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Configure CMake [Debug]
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-debug" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug  #  -T "ClangCl"
      - name: Build [Debug]
        run: cmake --build "${{github.workspace}}/build-debug" --config Debug -j   -- /m /nologo /verbosity:quiet
      - name: Test [Debug]
        working-directory: ${{github.workspace}}/build-debug
        run: ctest -C Debug --output-on-failure -j
      - name: Install [Debug]
        run: cmake --install "${{github.workspace}}/build-debug" --config Debug
      - name: Configure CMake [Release]
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build-release" -DCONVERTER_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release  #  -T "ClangCl"
      - name: Build [Release]
        run: cmake --build "${{github.workspace}}/build-release" --config Release -j   -- /m /nologo /verbosity:quiet
      - name: Test [Release]
        working-directory: ${{github.workspace}}/build-release
        run: ctest -C Release --verbose
      - name: Install [Release]
        run: cmake --install "${{github.workspace}}/build-release" --config Release


